import { faFootballBall, faBasketballBall, faBaseballBall, faVolleyballBall, faHockeyPuck, faBrush } from '@fortawesome/free-solid-svg-icons';


export const fonts = [
    { name: 'UnitedSansCond-Heavy', url: 'https://www.lax.ink/open_types/UnitedSansCond-Heavy.otf' },
    { name: 'UnitedSansCond-Light', url: 'https://www.lax.ink/open_types/UnitedSansCond-Light.otf' },
    { name: 'UnitedSansCond-Medium', url: 'https://www.lax.ink/open_types/UnitedSansCond-Medium.otf' },
    { name: 'UnitedSansCond-Bold', url: 'https://www.lax.ink/open_types/UnitedSansCond-Bold.otf' },
    { name: 'UnitedSansCond-Black', url: 'https://www.lax.ink/open_types/UnitedSansCond-Black.otf' },
  ]
  
  export const presetColors = [
    { value: '#E3002C', name: 'Red' },
    { value: '#b90b2f', name: 'Scarlet Red' },
    { value: '#862733', name: 'Crimson' },
    { value: '#783040', name: 'Burgundy' },
    { value: '#661D32', name: 'Deep Maroon' },
    { value: '#f47eb6', name: 'Light Pink' },
    { value: '#f04e99', name: 'Pink' },
    { value: '#F77D55', name: 'Peach' },
    { value: '#fe8101', name: 'Tenn. Orange' },
    { value: '#cb6114', name: 'Texas Orange' },
    { value: '#FC4C01', name: 'Orange' },
    { value: '#ea3301', name: 'Nike Orange' },
    { value: '#c4d600', name: 'Volt' },
    { value: '#ebff00', name: 'Neon Yellow' },
    { value: '#fbe120', name: 'Yellow' },
    { value: '#ffb81d', name: 'Athletic Gold' },
    { value: '#F2CFB1', name: 'Nude Tan' },
    { value: '#ceb889', name: 'Vegas Khaki Gold' },
    { value: '#85724d', name: 'Metallic Vegas' },
    { value: '#b2814e', name: 'Army Tan' },
    { value: '#5C6838', name: 'Army Green' },
    { value: '#d6d2c2', name: 'Cream' },
    { value: '#6e6258', name: 'Pewter' },
    { value: '#4f3529', name: 'Brown' },
    { value: '#124734', name: 'Forest Green' },
    { value: '#027b34', name: 'Kelly Green' },
    { value: '#01A92A', name: 'Lawn Green' },
    { value: '#42D72D', name: 'Neon Green' },
    { value: '#96d701', name: 'Lime Green' },
    { value: '#6bcdb6', name: 'Coastal Green' },
    { value: '#8be2cf', name: 'Mint' },
    { value: '#2BD5C3', name: 'Seafoam' },
    { value: '#00AEC6', name: 'Turquoise' },
    { value: '#019ca7', name: 'Teal' },
    { value: '#00a3de', name: 'Ice Light Blue' },
    { value: '#8bb7e7', name: 'Carolina Blue' },
    { value: '#4190de', name: 'Hopkins Blue' },
    { value: '#035db7', name: 'Mono Blue' },
    { value: '#0057B7', name: 'Light Royal Blue' },
    { value: '#013595', name: 'Royal Blue' },
    { value: '#022168', name: 'Cobalt Blue' },
    { value: '#13294C', name: 'Navy Blue' },
    { value: '#582c84', name: 'Purple' },
    { value: '#400185', name: 'NW Purple' },
    { value: '#AE94D1', name: 'Lavender' },
    { value: '#323f49', name: 'Dark Grey' },
    { value: '#A7BDD5', name: 'Glacier Grey' },
    { value: '#898d8e', name: 'Metallic Silver' },
    { value: '#9ea2a3', name: 'Grey' },
    { value: '#222223', name: 'Black' }
  ];
  
export const sportsIcons = [faFootballBall, faBasketballBall, faBaseballBall, faVolleyballBall, faHockeyPuck, faBrush];